### ISSUE TITLE
couldn't buildup repo successfully

### ISSUE THREAD

**Issue by akiratsuraii** [CVI-SZU/ME-GraphAU#12]
I'm new to machine learning, and I'm trying to get AU from real time cam with this project. However, I'm confused. I hope someone can help me out. 

1. I already downloaded all of the checkpoints and put into \ME-GraphAU-main\checkpoints and tried all the train command get the same error, how do i slove it ?
```
"...\ME-GraphAU-main\dataset.py", line 13, in <listcomp>
    images = [(image_list[i].strip(),  label_list[i, :]) for i in range(len_)]
IndexError: index 5 is out of bounds for axis 0 with size 5
```
2. Is it necessary to download everything in checkpoint.txt? readme didn't make it clear, I'm hoping someone can show me how to run from 0 to 100.
3. Can I run AU detection with the Pretrained models at google drive?

appreciate , wish all the best.

**Comment by zjutkarma** [comment]
Have you downloaded the BP4D or DISFA dataset? I think the error is about the lack of the image dataset.

**Comment by lingjivoo** [comment]
Hi, Have you downloaded BP4D or DISFA dataset?
