### ISSUE TITLE
OpenGrpahAU‘s pretrained model of  stage 2

### ISSUE THREAD

**Issue by zhiyiZhang1999** [CVI-SZU/ME-GraphAU#14]
Thank you for your great work! Could you publish the OpenGrpahAU‘s pretrained model of stage 2 later? Because some AU dataset is hard to get for training.

**Comment by lingjivoo** [comment]
Hi, I released the code and some checkpoints of OpenGrpahAU. And remaining checkpoints will be released in a few days.

**Comment by ymohamed08** [comment]
Can you not use stage one for AU classification as well, or what is the difference between both stages?

**Comment by lingjivoo** [comment]
Hi, please refer to our paper https://www.ijcai.org/proceedings/2022/0173.pdf . The first training stage aims to learn node features and the second stage is to learn multi-dimensional edge features (underlying relation) between each node pair.
