### ISSUE TITLE
A question about data preparation

### ISSUE THREAD

**Issue by pietromasur** [CVI-SZU/ME-GraphAU#2]
Hello, 
I am trying to run your code with DISFA, which by default comes with two folders: one with videos from right camera and the other with videos from the left camera. 
Which one of these folders should I place on the /img folder? 
Also, do I need to previously convert the videos into images in order to perform the training?

**Comment by lingjivoo** [comment]
We only use videos from left camera and perform face detection and alignment for each frame and crop it to 256 × 256 via MTCNN https://github.com/ipazc/mtcnn (or you could use other tools such as dlib and Retinaface https://github.com/biubug6/Pytorch_Retinaface).  You could see the image sample in data/DISFA/image/SN001/0.png, which is the first frame of LeftVideoSN001_comp.avi.

**Comment by pietromasur** [comment]
Thank you for your support!

**Comment by noirmist** [comment]
@lingjivoo Could you explain more detail about alignment? From the example I guess it is only use nose to align the faces, Am I right?

**Comment by sosohungry** [comment]
![image](https://user-images.githubusercontent.com/52829337/216986463-34888c30-6eda-4bbb-a852-0590cfec43ba.png)
it is 256 x 256 or 224 x 224 ?

**Comment by sosohungry** [comment]
`def detect_faces_2():
    # Check if the video was successfully opened
    if not video.isOpened():
        print("Could not open video")

    # Loop over the video frames
    while True:
        # Read a frame from the video
        ret, frame = video.read()

        # Check if we reached the end of the video
        if not ret:
            break

        # Do something with the frame, e.g., display it
        img = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

        detector = MTCNN()

        faces = detector.detect_faces(frame)

        for face in faces:
            x, y, w, h = face['box']
            print(x, y, w, h)
        
            max_length = max(w, h)  

            more_length = round(abs(w - h))

            # extract the face
            face_cropped = frame[y:y+h+more_length, x-more_length:x+w+more_length]
            
            # resize the face to 256x256
            face_resized = cv2.resize(face_cropped, (256, 256))
            
            # show the face
            cv2.imshow("Face", face_resized)
            cv2.waitKey(0)`
