### ISSUE TITLE
missing file: `mae_pretrain_checkpoint.pth`

### ISSUE THREAD

**Issue by sbelharbi** [CVI-SZU/ME-GraphAU#21]
hi,
thanks for this work.
is the file `/home/luocheng/pretrain_models/mae_pretrain_checkpoint.pth`, containing the initial weights for the model `mae_vit`, necessary?
they are used to initialize the weights.
i am trying to use the demo: `OpenGraphAU/demo.py` in https://github.com/CVI-SZU/ME-GraphAU/blob/main/OpenGraphAU/demo.py
since you provided the pre-trained weights for the hybrid datasets, `OpenGprahAU-maevit_second_stage.pth`, not sure how the very initial weights come into play. are they relevant? not sure if you finetuned the entire model or kept some weights identical to the initial weights from `mae_pretrain_checkpoint`.

if `mae_pretrain_checkpoint` is necessary, can you please provide a link to download it?

from the code, it seems that you finetuned the entire model:
https://github.com/CVI-SZU/ME-GraphAU/blob/fac11df714b7ef750683f22fbb5a9862f17cc4f7/OpenGraphAU/train_stage2.py#L98
to avoid initializing the model with `mae_pretrain_checkpoint`,
we can maybe just set `pretrained` in `pretrain_mae_base_patch16_224` to `False`?
https://github.com/CVI-SZU/ME-GraphAU/blob/fac11df714b7ef750683f22fbb5a9862f17cc4f7/OpenGraphAU/model/MEFL.py#L208

error log:
```bash
File "/home/ME-GraphAU/OpenGraphAU/demo.py", line 28, in main
    net = MEFARG(num_main_classes=conf.num_main_classes,
  File "/home/ME-GraphAU/OpenGraphAU/model/MEFL.py", line 212, in __init__
    self.backbone = pretrain_mae_base_patch16_224()
  File "/home/ME-GraphAU/OpenGraphAU/model/modeling_pretrain.py", line 331, in pretrain_mae_base_patch16_224
    checkpoint = torch.load(os.path.join(models_dir,
  File "/lib/python3.10/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/lib/python3.10/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/lib/python3.10/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/luocheng/pretrain_models/mae_pretrain_checkpoint.pth'
```

thanks

**Comment by lingjivoo** [comment]
Thank you for reaching out regarding model details. To clarify, we have fully fine-tuned all parameters of our model using pre-trained weights obtained through Masked Autoencoder (MAE) training. 

The MAE model weights can be downloaded directly from our shared drive: https://drive.google.com/file/d/1a4-Ninjdj_r_WgjzAnlAZNshJxIykFKU/view?usp=sharing

Please don't hesitate to reach out if you have any additional questions.

**Comment by sbelharbi** [comment]
thanks for the help.
closing.
