### ISSUE TITLE
训练速度很慢

### ISSUE THREAD

**Issue by sonwe1e** [CVI-SZU/ME-GraphAU#5]
你好，我想咨询一些关于训练的问题  
我将tool的文件处理完后得到了txt数据，然后开始用train_stage1.py训练，但训练总是会突然卡住再突然进行，在卡住的时候CPU和GPU占用率基本都为0%，我的设备是3060处理器，运行train_stage1.py在训练需要50分钟，验证需要10分钟，我想请问一下这种情况正常吗？  
谢谢你的回复

**Comment by lingjivoo** [comment]
你好， 谢谢对我们论文的关注。 我们在训练的时候 基于A100 GPU  第一阶段训练 基于ResNet-50的模型一轮时间约为7分钟  测试时间约为1-2分钟。 在3090显卡跑用时也差不多。  可能是您服务器I/O读取数据上出现了一些状况 也可以尝试将实验数据存放到固态硬盘上 或者调整下dataloder num_workers 数量

**Comment by sonwe1e** [comment]
感谢你的回复，确实应该是磁盘的调度问题，在GPU停止的时候磁盘会频繁的调取AU的图片，目前来说有两个问题
1. 之前提到的调整num_worker的数量确实有用，但是我们服务器的线程最大为8，所以会存在上限
2. 由于我们服务器的限制，我们希望自己优化一下数据加载的代码，请问有什么建议吗
￼
