### ISSUE TITLE
Hi, question about the F1 score report in paper

### ISSUE THREAD

**Issue by myt889** [CVI-SZU/ME-GraphAU#7]
Hi, thanks for sharing the code. I want to know how you report the  F1 score in the table of paper, did you choose the best epoch F1 score, or did you  chooese the top5 F1 score? Looking for your reply, I am new to this field.

**Comment by lingjivoo** [comment]
Hi, the early stop strategy is used for choosing weights.
More specifically, you can select the best validation result of one fold and record the number of the epoch and stop the training processes of the other folds according to it.
